Embedded Systems Library: UI Public Functions
UI Public Functions
UI
Functions
void UI_init ()
Initializes the UI API .
int UI_shouldEnterManut ()
Function to evaluate certain time, determines if the game should enter control mode.
void UI_waitForNoInput ()
Waits for the user to stop presseing any button.
void UI_resetScreen ()
Cleans the LCD.
void UI_manutMode ()
Show the dynamic menu and evaluates which control function to do.
void UI_showMenus ()
Switches between the calendar menu, and the best player menu. .
void UI_gameMode ()
Enters the game mode. .
Detailed Description
Function Documentation
UI_gameMode()
void UI_gameMode ()
Enters the game mode. .
Definition at line 682 of file ui.c.
References currentPlayer, evalLoss(), PlayerStruct::name, PlayerStruct::score, showScore(), TIME_TO_MOVE, UI_evalTimeOfObstacles(), UI_moveCar(), UI_resetObstacles(), and UI_setObstacles().
UI_init()
void UI_init ()
Initializes the UI API .
Note
This function must be called prior to any other UI functions.
Definition at line 705 of file ui.c.
References Adxl345_Init(), BUTTON_Init(), LCDText_Init(), myTime, RTC_Init(), RTC_SetValue(), UI_createCar(), and WAIT_Init().
UI_manutMode()
void UI_manutMode ()
Show the dynamic menu and evaluates which control function to do.
Definition at line 537 of file ui.c.
References BTN1_POSITION, BTN3_POSITION, BUTTON_GetButtonsEvents(), col, LCDText_Locate(), UI_erasePlayers(), UI_updateCalendar(), and writeManutMenu().
UI_resetScreen()
void UI_resetScreen ()
Cleans the LCD.
Definition at line 194 of file ui.c.
References LCDText_Clear().
Referenced by printTime(), setHighScore(), showScore(), UI_showBestPlayer(), UI_updateCalendar(), and writeManutMenu().
UI_shouldEnterManut()
int UI_shouldEnterManut ()
Function to evaluate certain time, determines if the game should enter control mode.
Definition at line 336 of file ui.c.
References BUTTON_Hit().
UI_showMenus()
void UI_showMenus ()
Switches between the calendar menu, and the best player menu. .
UI_waitForNoInput()
void UI_waitForNoInput ()
Waits for the user to stop presseing any button.
Definition at line 604 of file ui.c.
References BUTTON_Hit().
Referenced by setHighScore(), showScore(), and UI_erasePlayers().