Embedded Systems Library: C:/Users/obrun/Documents/MCUXpressoIDE_11.2.1_4149/SE1/SE2021/src/flash.c File Reference
flash.c File Reference
#include "flash.h"
Macros
#define IAP_LOCATION 0x1FFF1FF1
#define ERASE_SECTOR 52
#define COPY_TO_FLASH 51
#define PREPARE_WRITE 50
#define COMPARE 56
#define SECTOR_SIZE 30
Typedefs
typedef void(* IAP) (unsigned int[], unsigned int[])
Functions
unsigned int prepare_wr (unsigned int startSector, unsigned int endSector)
unsigned int FLASH_EraseSectors (unsigned int startSector, unsigned int endSector)
Erases sectors of flash memory.
unsigned int FLASH_WriteData (void *dstAddr, void *srcAddr, unsigned int size)
Writes data to determined space in flash memory.
unsigned int FLASH_VerifyData (void *dstAddr, void *srcAddr, unsigned int size)
Compares two memory addresses given a size.
Variables
const unsigned int sectors []
unsigned int command [5]
unsigned int output [5]
IAP iap_entry = (IAP) IAP_LOCATION
Macro Definition Documentation
COMPARE
#define COMPARE 56
Definition at line 18 of file flash.c.
COPY_TO_FLASH
#define COPY_TO_FLASH 51
Definition at line 16 of file flash.c.
ERASE_SECTOR
#define ERASE_SECTOR 52
Definition at line 15 of file flash.c.
IAP_LOCATION
#define IAP_LOCATION 0x1FFF1FF1
Definition at line 14 of file flash.c.
PREPARE_WRITE
#define PREPARE_WRITE 50
Definition at line 17 of file flash.c.
SECTOR_SIZE
#define SECTOR_SIZE 30
Definition at line 19 of file flash.c.
Typedef Documentation
IAP
typedef void(* IAP) (unsigned int[], unsigned int[])
Definition at line 52 of file flash.c.
Function Documentation
prepare_wr()
unsigned int prepare_wr (unsigned int startSector, unsigned int endSector)
Definition at line 55 of file flash.c.
References command, iap_entry, output, and PREPARE_WRITE.
Referenced by FLASH_EraseSectors(), and FLASH_WriteData().
Variable Documentation
command
unsigned int command[5]
Definition at line 50 of file flash.c.
Referenced by FLASH_EraseSectors(), FLASH_VerifyData(), FLASH_WriteData(), and prepare_wr().
iap_entry
IAP iap_entry = (IAP) IAP_LOCATION
Definition at line 53 of file flash.c.
Referenced by FLASH_EraseSectors(), FLASH_VerifyData(), FLASH_WriteData(), and prepare_wr().
output
unsigned int output[5]
Definition at line 51 of file flash.c.
Referenced by FLASH_EraseSectors(), FLASH_VerifyData(), FLASH_WriteData(), and prepare_wr().
sectors
const unsigned int sectors[]
Initial value:
= {0x0000000,
                                0x00001000,
                                0x00002000,
                                0x00003000,
                                0x00004000,
                                0x00005000,
                                0x00006000,
                                0x00007000,
                                0x00008000,
                                0x00009000,
                                0x0000A000,
                                0x0000B000,
                                0x0000C000,
                                0x0000D000,
                                0x0000E000,
                                0x0000F000,
                                0x00010000,
                                0x00018000,
                                0x00020000,
                                0x00028000,
                                0x00030000,
                                0x00038000,
                                0x00040000,
                                0x00048000,
                                0x00050000,
                                0x00058000,
                                0x00060000,
                                0x00068000,
                                0x00070000,
                                0x00078000}
Definition at line 20 of file flash.c.
Referenced by FLASH_WriteData().