Embedded Systems Library: C:/Users/obrun/Documents/MCUXpressoIDE_11.2.1_4149/SE1/SE2021/src/adxl345.c File Reference
adxl345.c File Reference
#include "spi.h"
#include "adxl345.h"
Macros
#define READ_MODE 1<<7
#define MB 1<<6
#define CS 24
#define READ_DEV_ID 0x80
#define BW_RATE 0x2c
#define POWER_CTL 0x2d
#define DATA_FORMAT 0x31
#define DATA_X0 0x32
#define DATA_X1 0x33
#define DATA_Y0 0x34
#define DATA_Y1 0x35
#define DATA_Z0 0x36
#define DATA_Z1 0x37
#define DEV_ID 229
Functions
void activeCs ()
void inactiveCs ()
void setCs ()
int AC_GetDeviceId ()
void config_bw_rate (unsigned short *arr)
void config_data_format (unsigned short *arr)
void config_power_ctl (unsigned short *arr)
int Adxl345_Init (void)
Initializes the adxl345 API to be aware of the the accelerometer.
short Adxl345_GetX ()
Gets the 2 byte X values of the accelerometer.
short Adxl345_GetY ()
Gets the 2 byte Y values of the accelerometer.
short Adcl345_GetZ ()
Gets the 2 byte Z values of the accelerometer.
Variables
unsigned short bw_rate_arr [] = {BW_RATE, 0x0c}
unsigned short power_ctl_arr [] = {POWER_CTL, 0x08}
unsigned short data_format_arr [] = {DATA_FORMAT, 0x00}
unsigned short getx_arr [] = {(READ_MODE | MB | DATA_X0), 0x00, 0x00}
unsigned short gety_arr [] = {(READ_MODE | MB | DATA_Y0), 0x00, 0x00}
unsigned short getz_arr [] = {(READ_MODE | MB | DATA_Z0), 0x00, 0x00}
unsigned short getid_arr [] = {READ_DEV_ID, 0x00}
Macro Definition Documentation
BW_RATE
#define BW_RATE 0x2c
Definition at line 21 of file adxl345.c.
CS
#define CS 24
Definition at line 18 of file adxl345.c.
DATA_FORMAT
#define DATA_FORMAT 0x31
Definition at line 23 of file adxl345.c.
DATA_X0
#define DATA_X0 0x32
Definition at line 24 of file adxl345.c.
DATA_X1
#define DATA_X1 0x33
Definition at line 25 of file adxl345.c.
DATA_Y0
#define DATA_Y0 0x34
Definition at line 26 of file adxl345.c.
DATA_Y1
#define DATA_Y1 0x35
Definition at line 27 of file adxl345.c.
DATA_Z0
#define DATA_Z0 0x36
Definition at line 28 of file adxl345.c.
DATA_Z1
#define DATA_Z1 0x37
Definition at line 29 of file adxl345.c.
DEV_ID
#define DEV_ID 229
Definition at line 30 of file adxl345.c.
MB
#define MB 1<<6
Definition at line 17 of file adxl345.c.
POWER_CTL
#define POWER_CTL 0x2d
Definition at line 22 of file adxl345.c.
READ_DEV_ID
#define READ_DEV_ID 0x80
Definition at line 20 of file adxl345.c.
READ_MODE
#define READ_MODE 1<<7
Definition at line 16 of file adxl345.c.
Function Documentation
AC_GetDeviceId()
int AC_GetDeviceId ()
Definition at line 50 of file adxl345.c.
References activeCs(), getid_arr, inactiveCs(), and SPI_Transfer().
Referenced by Adxl345_Init().
activeCs()
void activeCs ()
Definition at line 41 of file adxl345.c.
Referenced by AC_GetDeviceId(), Adcl345_GetZ(), Adxl345_GetX(), Adxl345_GetY(), config_bw_rate(), config_data_format(), and config_power_ctl().
config_bw_rate()
void config_bw_rate (unsigned short * arr)
Definition at line 57 of file adxl345.c.
References activeCs(), inactiveCs(), and SPI_Transfer().
Referenced by Adxl345_Init().
config_data_format()
void config_data_format (unsigned short * arr)
Definition at line 62 of file adxl345.c.
References activeCs(), inactiveCs(), and SPI_Transfer().
Referenced by Adxl345_Init().
config_power_ctl()
void config_power_ctl (unsigned short * arr)
Definition at line 67 of file adxl345.c.
References activeCs(), inactiveCs(), and SPI_Transfer().
Referenced by Adxl345_Init().
inactiveCs()
void inactiveCs ()
Definition at line 42 of file adxl345.c.
Referenced by AC_GetDeviceId(), Adcl345_GetZ(), Adxl345_GetX(), Adxl345_GetY(), config_bw_rate(), config_data_format(), and config_power_ctl().
setCs()
void setCs ()
Definition at line 43 of file adxl345.c.
References CS.
Referenced by Adxl345_Init().
Variable Documentation
bw_rate_arr
unsigned short bw_rate_arr[] = {BW_RATE, 0x0c}
Definition at line 32 of file adxl345.c.
Referenced by Adxl345_Init().
data_format_arr
unsigned short data_format_arr[] = {DATA_FORMAT, 0x00}
Definition at line 34 of file adxl345.c.
Referenced by Adxl345_Init().
getid_arr
unsigned short getid_arr[] = {READ_DEV_ID, 0x00}
Definition at line 40 of file adxl345.c.
Referenced by AC_GetDeviceId().
getx_arr
unsigned short getx_arr[] = {(READ_MODE | MB | DATA_X0), 0x00, 0x00}
Definition at line 36 of file adxl345.c.
Referenced by Adxl345_GetX().
gety_arr
unsigned short gety_arr[] = {(READ_MODE | MB | DATA_Y0), 0x00, 0x00}
Definition at line 37 of file adxl345.c.
Referenced by Adxl345_GetY().
getz_arr
unsigned short getz_arr[] = {(READ_MODE | MB | DATA_Z0), 0x00, 0x00}
Definition at line 38 of file adxl345.c.
Referenced by Adcl345_GetZ().
power_ctl_arr
unsigned short power_ctl_arr[] = {POWER_CTL, 0x08}
Definition at line 33 of file adxl345.c.
Referenced by Adxl345_Init().