Embedded Systems Library: LCD Public Functions
LCD Public Functions
LCD
Functions
void LCDText_Init (void)
Initiliazes the communication with the display using lines and 16 rows.
void LCDText_WriteChar (char ch)
Writes a character to the display in the cursor position.
void LCDText_WriteString (char *str)
Writes a string (word) to the display in the cursor position.
void LCDText_Locate (int row, int column)
Moves the cursor to the position received in arguments.
void LCDText_Clear (void)
Clears the display using the command in the display API.
void LCDText_CreateChar (unsigned char location, unsigned char charmap[])
Creates a new character to the display.
void LCDText_Printf (char *fmt,...)
Writes in the LCD in similar way that the c printf does.
Detailed Description
Function Documentation
LCDText_Clear()
void LCDText_Clear (void)
Clears the display using the command in the display API.
Definition at line 130 of file lcd.c.
Referenced by UI_erasePlayers(), and UI_resetScreen().
LCDText_CreateChar()
void LCDText_CreateChar (unsigned char location, unsigned char charmap[])
Creates a new character to the display.
Parameters
location Place where the new character is going to be.
charmap[] Bitmap representation of the pixels witch represents the new character.
Definition at line 137 of file lcd.c.
Referenced by UI_createCar().
LCDText_Init()
void LCDText_Init (void)
Initiliazes the communication with the display using lines and 16 rows.
Definition at line 64 of file lcd.c.
References DATA_4, DATA_5, DATA_6, DATA_7, ENABLE, ENABLE_DATA_4, ENABLE_DATA_5, ENABLE_DATA_6, ENABLE_DATA_7, ENABLE_RS, ENABLE_SEL, RS, and WAIT_Milliseconds().
Referenced by UI_init().
LCDText_Locate()
void LCDText_Locate (int row, int column)
Moves the cursor to the position received in arguments.
Parameters
row Positions the cursor in this row of the display.
column Positions the cursor in this column of the display.
Definition at line 88 of file lcd.c.
References col, and lin.
Referenced by incrementColumn(), printTime(), setHighScore(), showObstacles(), showScore(), UI_erasePlayers(), UI_manutMode(), UI_moveCar(), UI_updateCalendar(), writeManutMenu(), and writePlayers().
LCDText_Printf()
void LCDText_Printf (char * fmt, ...)
Writes in the LCD in similar way that the c printf does.
Parameters
fmt The format in which the rest of the args must correspond to, see how printf is called, it works the same way.
... The arguments to be printed.
Definition at line 149 of file lcd.c.
References LCDText_WriteString().
Referenced by printTime(), setHighScore(), showScore(), and writePlayers().
LCDText_WriteChar()
void LCDText_WriteChar (char ch)
Writes a character to the display in the cursor position.
Parameters
ch Character to be written
Definition at line 118 of file lcd.c.
Referenced by LCDText_WriteString(), UI_moveCar(), and writeManutMenu().
LCDText_WriteString()
void LCDText_WriteString (char * str)
Writes a string (word) to the display in the cursor position.
Parameters
str Word to be written.
Definition at line 124 of file lcd.c.
References LCDText_WriteChar().
Referenced by LCDText_Printf(), setHighScore(), showObstacles(), UI_erasePlayers(), UI_moveCar(), and writeManutMenu().