Embedded Systems Library: C:/Users/obrun/Documents/MCUXpressoIDE_11.2.1_4149/SE1/SE2021/src/ui.c File Reference
ui.c File Reference
#include "ui.h"
#include "wait.h"
#include "lcd.h"
#include "rtc.h"
#include "flash.h"
#include "spi.h"
#include "adxl345.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include <button.h>
Data Structures
struct PlayerStruct
Macros
#define BTN3_POSITION 3
#define BTN2_POSITION 12
#define BTN1_POSITION 48
#define MAX_OBS 5
#define TIME_TO_MOVE 3000
#define NUMBER_OF_SCORES 3
#define AXIS_REPEAT 2
#define AXIS_MOVE 0
#define AXIS_CHANGE 1
Functions
void decHour (struct tm *nowTime)
void decMin (struct tm *nowTime)
void decSec (struct tm *nowTime)
void decDay (struct tm *nowTime)
void decMon (struct tm *nowTime)
void decYear (struct tm *nowTime)
void incHour (struct tm *nowTime)
void incMin (struct tm *nowTime)
void incSec (struct tm *nowTime)
void incDay (struct tm *nowTime)
void incMon (struct tm *nowTime)
void incYear (struct tm *nowTime)
void UI_resetScreen ()
Cleans the LCD.
int containsSame (unsigned int *positions, int count, int src)
void getRandomPositions (unsigned int *positions, int min, int max, int count)
void setRandomPositions ()
void setTopObs ()
void copyIntArray (unsigned int *dst, unsigned int *src, int size)
void setBotObs ()
void showObstacles ()
void printTime (struct tm *nowTime)
void UI_setObstacles ()
int UI_evalTimeOfObstacles ()
int evalTimeToFlip ()
void UI_showTime ()
void writePlayers ()
void UI_showBestPlayer ()
void UI_showMenus (int timeWhenFlip)
void UI_resetObstacles ()
int UI_shouldEnterManut ()
Function to evaluate certain time, determines if the game should enter control mode.
void UI_createCar ()
int getXStateRight ()
int getXStateLeft ()
void UI_moveCar ()
void UI_erasePlayers ()
void writeManutMenu ()
void UI_updateCalendar ()
void UI_manutMode ()
Show the dynamic menu and evaluates which control function to do.
void UI_waitForNoInput ()
Waits for the user to stop presseing any button.
void setHighScore (int index)
int evalScore ()
void showScore ()
int evalLoss ()
void UI_gameMode ()
Enters the game mode. .
void UI_init ()
Initializes the UI API .
Variables
unsigned int timeOnTran = 0
unsigned int carPos = 7
unsigned int timeCounter = 0
unsigned int flipMenuTimer = 0
unsigned int positionsToBeEvaluated [MAX_OBS]
unsigned int randomPositions [MAX_OBS]
int * sectorAddr = 0x00078000
const int sectorAddr_val = 0x00078000
struct tm myTime
char topObs [17] = {' ',' ' ,' ', ' ',' ',' ',' ',' ' ,' ' ,' ' , ' ',' ' ,' ' ,' ' ,' ' ,' ',0 }
char botObs [17] = {' ',' ' ,' ', ' ',' ',' ',' ',' ' ,' ' ,' ' , ' ',' ' ,' ' ,' ' ,' ' ,' ' ,0}
char letters [27] = {'A' ,'B' ,'C' ,'D' ,'E' ,'F' ,'G' ,'H' ,'I','J' ,'K' ,'L' ,'M' ,'N' ,'O' ,'P' ,'Q' ,'R' ,'S' ,'T','U','V','W','X', 'Y', 'Z',0}
struct PlayerStruct playerStruct
struct PlayerStruct dummyPlayer = { .name ="AAA", .score=0}
struct PlayerStruct playerScores [NUMBER_OF_SCORES]
struct PlayerStruct * flashPlayerScores = (struct PlayerStruct*)sectorAddr_val
struct PlayerStruct currentPlayer = { .name = "AAA", .score = 0}
unsigned int leftState = AXIS_MOVE
unsigned int rightState = AXIS_MOVE
Macro Definition Documentation
AXIS_CHANGE
#define AXIS_CHANGE 1
Definition at line 359 of file ui.c.
AXIS_MOVE
#define AXIS_MOVE 0
Definition at line 358 of file ui.c.
AXIS_REPEAT
#define AXIS_REPEAT 2
Definition at line 357 of file ui.c.
BTN1_POSITION
#define BTN1_POSITION 48
Definition at line 27 of file ui.c.
BTN2_POSITION
#define BTN2_POSITION 12
Definition at line 26 of file ui.c.
BTN3_POSITION
#define BTN3_POSITION 3
Definition at line 25 of file ui.c.
MAX_OBS
#define MAX_OBS 5
Definition at line 28 of file ui.c.
NUMBER_OF_SCORES
#define NUMBER_OF_SCORES 3
Definition at line 30 of file ui.c.
TIME_TO_MOVE
#define TIME_TO_MOVE 3000
Definition at line 29 of file ui.c.
Function Documentation
containsSame()
int containsSame (unsigned int * positions, int count, int src)
Definition at line 205 of file ui.c.
Referenced by getRandomPositions(), and setTopObs().
copyIntArray()
void copyIntArray (unsigned int * dst, unsigned int * src, int size)
Definition at line 237 of file ui.c.
Referenced by setBotObs().
decDay()
void decDay (struct tm * nowTime)
Definition at line 87 of file ui.c.
Referenced by UI_updateCalendar().
decHour()
void decHour (struct tm * nowTime)
Definition at line 66 of file ui.c.
Referenced by UI_updateCalendar().
decMin()
void decMin (struct tm * nowTime)
Definition at line 73 of file ui.c.
Referenced by UI_updateCalendar().
decMon()
void decMon (struct tm * nowTime)
Definition at line 118 of file ui.c.
Referenced by UI_updateCalendar().
decSec()
void decSec (struct tm * nowTime)
Definition at line 80 of file ui.c.
Referenced by UI_updateCalendar().
decYear()
void decYear (struct tm * nowTime)
Definition at line 125 of file ui.c.
Referenced by UI_updateCalendar().
evalLoss()
int evalLoss ()
Definition at line 677 of file ui.c.
References botObs, and carPos.
Referenced by UI_gameMode().
evalScore()
int evalScore ()
Definition at line 650 of file ui.c.
References currentPlayer, flashPlayerScores, NUMBER_OF_SCORES, and PlayerStruct::score.
Referenced by showScore().
evalTimeToFlip()
int evalTimeToFlip ()
Definition at line 286 of file ui.c.
References flipMenuTimer, and WAIT_GetElapsedMillis().
Referenced by UI_showMenus().
getRandomPositions()
void getRandomPositions (unsigned int * positions, int min, int max, int count)
Definition at line 212 of file ui.c.
References containsSame(), and WAIT_GetElapsedMillis().
Referenced by setRandomPositions().
getXStateLeft()
int getXStateLeft ()
Definition at line 388 of file ui.c.
References Adxl345_GetX(), AXIS_CHANGE, AXIS_MOVE, AXIS_REPEAT, and leftState.
Referenced by UI_moveCar().
getXStateRight()
int getXStateRight ()
Definition at line 365 of file ui.c.
References Adxl345_GetX(), AXIS_CHANGE, AXIS_MOVE, AXIS_REPEAT, and rightState.
Referenced by UI_moveCar().
incDay()
void incDay (struct tm * nowTime)
Definition at line 151 of file ui.c.
Referenced by UI_updateCalendar().
incHour()
void incHour (struct tm * nowTime)
Definition at line 132 of file ui.c.
Referenced by UI_updateCalendar().
incMin()
void incMin (struct tm * nowTime)
Definition at line 139 of file ui.c.
Referenced by UI_updateCalendar().
incMon()
void incMon (struct tm * nowTime)
Definition at line 181 of file ui.c.
Referenced by UI_updateCalendar().
incSec()
void incSec (struct tm * nowTime)
Definition at line 145 of file ui.c.
Referenced by UI_updateCalendar().
incYear()
void incYear (struct tm * nowTime)
Definition at line 187 of file ui.c.
Referenced by UI_updateCalendar().
printTime()
void printTime (struct tm * nowTime)
Definition at line 255 of file ui.c.
References LCDText_Locate(), LCDText_Printf(), and UI_resetScreen().
Referenced by UI_showTime(), and UI_updateCalendar().
setBotObs()
void setBotObs ()
Definition at line 243 of file ui.c.
References botObs, copyIntArray(), MAX_OBS, positionsToBeEvaluated, randomPositions, and topObs.
Referenced by UI_setObstacles().
setHighScore()
void setHighScore (int index)
Definition at line 608 of file ui.c.
References BTN1_POSITION, BTN3_POSITION, BUTTON_GetButtonsEvents(), currentPlayer, FLASH_EraseSectors(), FLASH_WriteData(), LCDText_Locate(), LCDText_Printf(), LCDText_WriteString(), letters, PlayerStruct::name, playerScores, sectorAddr, UI_resetScreen(), and UI_waitForNoInput().
Referenced by showScore().
setRandomPositions()
void setRandomPositions ()
Definition at line 224 of file ui.c.
References getRandomPositions(), MAX_OBS, and randomPositions.
Referenced by UI_setObstacles().
setTopObs()
void setTopObs ()
Definition at line 228 of file ui.c.
References containsSame(), MAX_OBS, randomPositions, and topObs.
Referenced by UI_setObstacles().
showObstacles()
void showObstacles ()
Definition at line 248 of file ui.c.
References botObs, LCDText_Locate(), LCDText_WriteString(), and topObs.
Referenced by UI_setObstacles().
showScore()
void showScore ()
Definition at line 663 of file ui.c.
References currentPlayer, evalScore(), LCDText_Locate(), LCDText_Printf(), PlayerStruct::score, setHighScore(), UI_resetScreen(), UI_waitForNoInput(), and WAIT_Milliseconds().
Referenced by UI_gameMode().
UI_createCar()
void UI_createCar ()
Definition at line 352 of file ui.c.
References LCDText_CreateChar().
Referenced by UI_init().
UI_erasePlayers()
void UI_erasePlayers ()
Definition at line 444 of file ui.c.
References dummyPlayer, FLASH_EraseSectors(), FLASH_WriteData(), LCDText_Clear(), LCDText_Locate(), LCDText_WriteString(), NUMBER_OF_SCORES, playerScores, sectorAddr, UI_waitForNoInput(), and WAIT_Milliseconds().
Referenced by UI_manutMode().
UI_evalTimeOfObstacles()
int UI_evalTimeOfObstacles ()
Definition at line 280 of file ui.c.
References timeCounter, and WAIT_GetElapsedMillis().
Referenced by UI_gameMode().
UI_moveCar()
void UI_moveCar ()
Definition at line 411 of file ui.c.
References AXIS_MOVE, BUTTON_GetButtonsEvents(), carPos, getXStateLeft(), getXStateRight(), LCDText_Locate(), LCDText_WriteChar(), and LCDText_WriteString().
Referenced by UI_gameMode().
UI_resetObstacles()
void UI_resetObstacles ()
Definition at line 329 of file ui.c.
References botObs, timeCounter, and topObs.
Referenced by UI_gameMode().
UI_setObstacles()
void UI_setObstacles ()
Definition at line 272 of file ui.c.
References setBotObs(), setRandomPositions(), setTopObs(), showObstacles(), and timeCounter.
Referenced by UI_gameMode().
UI_showBestPlayer()
void UI_showBestPlayer ()
Definition at line 313 of file ui.c.
References UI_resetScreen(), and writePlayers().
Referenced by UI_showMenus().
UI_showMenus()
void UI_showMenus (int timeWhenFlip)
Definition at line 318 of file ui.c.
References evalTimeToFlip(), flipMenuTimer, UI_showBestPlayer(), and UI_showTime().
UI_showTime()
void UI_showTime ()
Definition at line 292 of file ui.c.
References printTime(), RTC_GetValue(), and WAIT_Milliseconds().
Referenced by UI_showMenus().
UI_updateCalendar()
void UI_updateCalendar ()
Definition at line 466 of file ui.c.
References BTN1_POSITION, BTN3_POSITION, BUTTON_GetButtonsEvents(), col, decDay(), decHour(), decMin(), decMon(), decSec(), decYear(), incDay(), incHour(), incMin(), incMon(), incSec(), incYear(), LCDText_Locate(), printTime(), RTC_GetValue(), RTC_SetValue(), and UI_resetScreen().
Referenced by UI_manutMode().
writeManutMenu()
void writeManutMenu ()
Definition at line 458 of file ui.c.
References LCDText_Locate(), LCDText_WriteChar(), LCDText_WriteString(), and UI_resetScreen().
Referenced by UI_manutMode().
writePlayers()
void writePlayers ()
Definition at line 298 of file ui.c.
References flashPlayerScores, LCDText_Locate(), LCDText_Printf(), and WAIT_Milliseconds().
Referenced by UI_showBestPlayer().
Variable Documentation
botObs
char botObs[17] = {' ',' ' ,' ', ' ',' ',' ',' ',' ' ,' ' ,' ' , ' ',' ' ,' ' ,' ' ,' ' ,' ' ,0}
Definition at line 50 of file ui.c.
Referenced by evalLoss(), setBotObs(), showObstacles(), and UI_resetObstacles().
carPos
unsigned int carPos = 7
Definition at line 32 of file ui.c.
Referenced by evalLoss(), and UI_moveCar().
currentPlayer
struct PlayerStruct currentPlayer = { .name = "AAA", .score = 0}
Definition at line 63 of file ui.c.
Referenced by evalScore(), setHighScore(), showScore(), and UI_gameMode().
dummyPlayer
struct PlayerStruct dummyPlayer = { .name ="AAA", .score=0}
Definition at line 57 of file ui.c.
Referenced by UI_erasePlayers().
flashPlayerScores
struct PlayerStruct* flashPlayerScores = (struct PlayerStruct*)sectorAddr_val
Definition at line 61 of file ui.c.
Referenced by evalScore(), and writePlayers().
flipMenuTimer
unsigned int flipMenuTimer = 0
Definition at line 34 of file ui.c.
Referenced by evalTimeToFlip(), and UI_showMenus().
leftState
unsigned int leftState = AXIS_MOVE
Definition at line 360 of file ui.c.
Referenced by getXStateLeft().
letters
char letters[27] = {'A' ,'B' ,'C' ,'D' ,'E' ,'F' ,'G' ,'H' ,'I','J' ,'K' ,'L' ,'M' ,'N' ,'O' ,'P' ,'Q' ,'R' ,'S' ,'T','U','V','W','X', 'Y', 'Z',0}
Definition at line 51 of file ui.c.
Referenced by setHighScore().
myTime
struct tm myTime
Initial value:
= {.tm_sec=0,
        .tm_min=0,
        .tm_hour=0,
        .tm_mday=1,
        .tm_wday=0,
        .tm_yday=0,
        .tm_mon=0,
        .tm_year = 2020 - 1900,
        .tm_isdst=0
}
Definition at line 39 of file ui.c.
Referenced by UI_init().
playerScores
struct PlayerStruct playerScores[NUMBER_OF_SCORES]
Definition at line 59 of file ui.c.
Referenced by setHighScore(), and UI_erasePlayers().
playerStruct
struct PlayerStruct playerStruct
positionsToBeEvaluated
unsigned int positionsToBeEvaluated[MAX_OBS]
Definition at line 35 of file ui.c.
Referenced by setBotObs().
randomPositions
unsigned int randomPositions[MAX_OBS]
Definition at line 36 of file ui.c.
Referenced by setBotObs(), setRandomPositions(), and setTopObs().
rightState
unsigned int rightState = AXIS_MOVE
Definition at line 361 of file ui.c.
Referenced by getXStateRight().
sectorAddr
int* sectorAddr = 0x00078000
Definition at line 37 of file ui.c.
Referenced by setHighScore(), and UI_erasePlayers().
sectorAddr_val
const int sectorAddr_val = 0x00078000
Definition at line 38 of file ui.c.
timeCounter
unsigned int timeCounter = 0
Definition at line 33 of file ui.c.
Referenced by UI_evalTimeOfObstacles(), UI_resetObstacles(), and UI_setObstacles().
timeOnTran
unsigned int timeOnTran = 0
Definition at line 31 of file ui.c.
topObs
char topObs[17] = {' ',' ' ,' ', ' ',' ',' ',' ',' ' ,' ' ,' ' , ' ',' ' ,' ' ,' ' ,' ' ,' ',0 }
Definition at line 49 of file ui.c.
Referenced by setBotObs(), setTopObs(), showObstacles(), and UI_resetObstacles().