Embedded Systems Library: ADXL345 Public Functions
ADXL345 Public Functions
ADXL345
Functions
int Adxl345_Init (void)
Initializes the adxl345 API to be aware of the the accelerometer.
short Adxl345_GetX (void)
Gets the 2 byte X values of the accelerometer.
short Adxl345_GetY (void)
Gets the 2 byte Y values of the accelerometer.
short Adcl345_GetZ (void)
Gets the 2 byte Z values of the accelerometer.
void SPI_Init (void)
Initializes the spi API.
void SPI_ConfigTransfer (int frequency, int bitData, int mode)
Configures the way spi is going to transfer data.
int SPI_Transfer (unsigned short *txBuffer, short *rxBuffer, int lenght)
Transfers bits in wich the spi is in contact to.
Detailed Description
Function Documentation
Adcl345_GetZ()
short Adcl345_GetZ (void)
Gets the 2 byte Z values of the accelerometer.
Definition at line 113 of file adxl345.c.
References activeCs(), getz_arr, inactiveCs(), and SPI_Transfer().
Adxl345_GetX()
short Adxl345_GetX (void)
Gets the 2 byte X values of the accelerometer.
Definition at line 89 of file adxl345.c.
References activeCs(), getx_arr, inactiveCs(), and SPI_Transfer().
Referenced by getXStateLeft(), and getXStateRight().
Adxl345_GetY()
short Adxl345_GetY (void)
Gets the 2 byte Y values of the accelerometer.
Definition at line 101 of file adxl345.c.
References activeCs(), gety_arr, inactiveCs(), and SPI_Transfer().
Adxl345_Init()
int Adxl345_Init (void)
Initializes the adxl345 API to be aware of the the accelerometer.
Note
This function must be called prior to any other ADXL345 functions.
Definition at line 74 of file adxl345.c.
References AC_GetDeviceId(), bw_rate_arr, config_bw_rate(), config_data_format(), config_power_ctl(), data_format_arr, DEV_ID, power_ctl_arr, setCs(), SPI_ConfigTransfer(), and SPI_Init().
Referenced by UI_init().
SPI_ConfigTransfer()
void SPI_ConfigTransfer (int frequency, int bitData, int mode)
Configures the way spi is going to transfer data.
Parameters
frequency Frequency of my spi, which divided by the system clock should be an even number bigger then 8.
bitData Specifies the number of bits im going to transfer.
mode Chooses the spi mode, specified in the first two bits. 1=cpha, 2=cpol,3=cpha|cpol.
Definition at line 38 of file spi.c.
References BITS, CPHA, CPOL, dummy, ENABLE, and MASTER.
Referenced by Adxl345_Init().
SPI_Init()
void SPI_Init (void)
Initializes the spi API.
Note
This function must be called prior to any other spi functions.
Definition at line 26 of file spi.c.
References MISO, MOSI, and SCK.
Referenced by Adxl345_Init().
SPI_Transfer()
int SPI_Transfer (unsigned short * txBuffer, short * rxBuffer, int lenght)
Transfers bits in wich the spi is in contact to.
Parameters
txBuffer Buffer containing the data to the slave.
rxBuffer Buffer containing the slave answer.
lenght Size of txBuffer.
Definition at line 59 of file spi.c.
References dummy, ERROR_FLAGS, and SPIF.
Referenced by AC_GetDeviceId(), Adcl345_GetZ(), Adxl345_GetX(), Adxl345_GetY(), config_bw_rate(), config_data_format(), and config_power_ctl().